### PR TITLE
Detect references to undef Kconfig symbols in samples and tests (and not just the main tree)

### PR DESCRIPTION
**Pull request by ulfalizer**
Main commit:

```
check_compliance.py: Detect refs to undef. symbols in samples and tests

Extend the check for references to undefined Kconfig symbols to also
detect undefined symbols in samples and tests.

Samples and tests were skipped due to using separate Kconfig trees,
which hid the symbols defined in them. Work around it by grepping for
Kconfig symbol definitions in them instead.

Keep properly parsing the main Kconfig tree, as it's needed to see
symbol names that are stitched together with the Kconfig preprocessor.
```

Cleanup:

```
check_compliance.py: Simplify Kconfig tests with git() helper

Use the git() helper instead instead of subprocess.Popen to get rid of
some code duplication.

Also add some more comments to the Kconfig tests.
```

Needs these to be merged/fixed before it can be used:

  - https://github.com/zephyrproject-rtos/zephyr/pull/20683
  - https://github.com/zephyrproject-rtos/zephyr/pull/20682
  - https://github.com/zephyrproject-rtos/zephyr/issues/20681

### CODE REVIEW

**Comment by ulfalizer** [comment]
Ping

**Comment by ulfalizer** [comment]
Oh... needs rebase.

**Comment by ulfalizer** [comment]
Rebased now

**Comment by carlescufi** [comment]
@nashif can you take a look?

**Comment by nashif** [comment]
rebase

**Comment by ulfalizer** [comment]
> rebase

Will do

**Comment by ulfalizer** [comment]
Rebased now.

https://github.com/zephyrproject-rtos/ci-tools/pull/115 needs to go in to break `check_compliance.py` too.

**Comment by ulfalizer** [comment]
Rebased and passing. Should be fine to merge.

**Pull request merged**
