### PR TITLE
check_compliance.py: Avoid more false positives in Kconfig check

### PR DESCRIPTION
**Pull request by ulfalizer**
Add more patterns to the negative lookahead in the regex, to avoid
flagging CMake variable expansion (`CONFIG_FOO_${VAR}`), CMake
`configure_file()` references (`CONFIG_FOO_@VAR@`), Python `format()` stuff
(`"CONFIG_FOO_{}_...".format(...)`), and `#endif` comments that talk about
many symbols (`#endif /* CONFIG_FOO_* */`).

This gets rid of some entries from the whitelist too.

Mention the safe #endif format in the message posted when the test
fails.

Prompted by https://github.com/zephyrproject-rtos/zephyr/pull/16222.

### CODE REVIEW

**Comment by ulfalizer** [comment]
CC @Sizurka

**Comment by Sizurka** [comment]
You may want to explicitly escape the `{` in the lookahead, since that's also also a reserved character.  The git parser is apparently smart enough to pass it through, since there it's not of the form `{N}` or `{N,M}` (either as repetition of a modifier).  But that's not guaranteed behavior (i.e. Perl itself will throw a syntax error if you try that).

**Comment by ulfalizer** [comment]
@Sizurka 
Fixed.

I broadened it a bit to just look for `$` instead of `${`, and switched to a character set. Probably unlikely that `CONFIG_FOO` is referenced as `CONFIG_FOO$` (though it might for super-obscure cases with shell scripts maybe...).

**Comment by ulfalizer** [comment]
@marc-hb 
I still think the regexp is quicker to understand and tweak than doing it manually in Python, even if it was without comments (plus it's neater to do it in one place). I just like commenting a lot.

Most of the comments explain why those particular characters were picked too. Would still get those with Python I guess.

**Comment by ulfalizer** [comment]
Hmm... think you'd also need to capture some context around the match to implement the same thing in Python. That offsets it more, IMO.

**Comment by ulfalizer** [comment]
@marc-hb 
Are you okay with merging this version? Would be nice so that https://github.com/zephyrproject-rtos/zephyr/pull/16222 can go in.

**Comment by marc-hb** [comment]
> Are you okay with merging this version?

For the record yes I was, I would have "requested changes" otherwise. I didn't see it was blocking the other PR sorry.

**Pull request merged**
