### PR TITLE
Be alive

### PR DESCRIPTION
**Pull request by ulfalizer**
We need to fix our CI so that it doesn't just silently do nothing on most errors.

### CODE REVIEW

**Comment by mbolivar** [comment]
What exactly is the problem? Why are these patches being reverted?

**Comment by ulfalizer** [comment]
> What exactly is the problem?

CI isn't running. It usually does on this repo too: https://github.com/zephyrproject-rtos/ci-tools/pull/37#issuecomment-474979313

Seeing if it's something that was added recently that broke it.

**Comment by ulfalizer** [comment]
@mbolivar 
Did anything west-related change recently that might've broken this?

**Comment by ulfalizer** [comment]
It just posted a message on https://github.com/zephyrproject-rtos/ci-tools/pull/79. I wonder if it's just being extremely slow.

**Pull request closed without merging**
