### PR TITLE
Run the dtlib and edtlib test suites in CI

### PR DESCRIPTION
**Pull request by ulfalizer**
zephyrproject-rtos/zephyr#17660 must go in
before this will work.

Piggyback a clarification re. ZEPHYR_BASE being None when not running on
a Zephyr tree (e.g. when running on the ci-tools repo itself).

### CODE REVIEW

**Comment by ulfalizer** [comment]
@galak 
Yep, but it runs in a fraction of a second, so it's not an issue.

**Comment by carlescufi** [comment]
Is this something that should be in the  compliance check or rather in CI itself, like the west unit tests?

**Comment by ulfalizer** [comment]
@carlescufi 
What do you mean by "in CI itself"? This is the only way of running tests that I know about. Do we need several?

It's testing dtlib and edtlib lib themselves. The important thing to me is that a message shows up on GitHub if you break them. Hiding it in a log would be wasting people's time.

**Comment by ulfalizer** [comment]
I'll probably add global checks for the Zephyr code later as well, like for Kconfig, if it's the word "compliance" that bothers you (broken code is non-compliant).

Regardless of what we call them, this type of test is the right place to do it, to make things nicer for users.

**Comment by carlescufi** [comment]
@galak can you please take a look and merge if you have no objections?

**Comment by galak** [comment]
Merging, but we need to clean this up in the future so this isn't run on every PR.

**Pull request merged**
